In [1]:
import os
import pathlib
import pandas as pd

In [2]:
cols_prop = [
    "Asteroid_id",
    "H",
    "a_p",
    "e_p",
    "sin_i_p",
    "n",
    "g",
    "s",
    "LCE",
    "My"
]

In [3]:
core_path = os.getcwd()
prop_df = pd.read_csv("data/lvl0/proper_elements.syn", delimiter='\s+', skiprows=2, names=cols_prop)

/tmp/ipykernel_13846/1169933713.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  prop_df = pd.read_csv("data/lvl0/proper_elements.syn", delimiter='\s+', skiprows=2, names=cols_prop)

In [4]:
prop_df.head()

,Asteroid_id,H,a_p,e_p,sin_i_p,n,g,s,LCE,My
0,1,3.41,2.767096,0.116198,0.167585,78.193318,54.070272,-59.170034,1.16,-2
1,2,4.17,2.770918,0.281258,0.547547,78.041654,-1.335344,-46.393342,44.20,10
2,3,5.36,2.669366,0.233506,0.229226,82.528181,43.635655,-61.222138,13.74,-2
3,4,3.31,2.361513,0.098758,0.111336,99.188833,36.872897,-39.597863,2.83,2
4,6,5.76,2.425271,0.158486,0.247863,95.303184,31.568209,-41.829042,4.56,2

In [5]:
prop_df.dtypes

Asteroid_id     object
H              float64
a_p            float64
e_p            float64
sin_i_p        float64
n              float64
g              float64
s              float64
LCE            float64
My               int64
dtype: object

In [6]:
cols_fam = [
    "Asteroid_id",
    "H",
    "status",
    "family_1",
    "dv_fam_1",
    "near_1",
    "family_2",
    "dv_fam_2",
    "near_2",
    "rescod"
]

In [7]:
family_df = pd.read_csv("data/lvl0/family_classification.famrec", delimiter='\s+', names=cols_fam, comment='%')

/tmp/ipykernel_13846/1226158463.py:1: DtypeWarning: Columns (0,5) have mixed types. Specify dtype option on import or set low_memory=False.
  family_df = pd.read_csv("data/lvl0/family_classification.famrec", delimiter='\s+', names=cols_fam, comment='%')

In [8]:
family_df.head()

,Asteroid_id,H,status,family_1,dv_fam_1,near_1,family_2,dv_fam_2,near_2,rescod
0,1,3.41,0,0,0.0,0,0,0.0,0,0
1,2,4.17,3,2,0.0,0,0,0.0,0,0
2,3,5.36,3,3,0.0,0,0,0.0,0,0
3,4,3.31,3,4,0.0,0,0,0.0,0,0
4,5,6.93,3,5,0.0,0,0,0.0,0,0

In [9]:
family_df.dtypes

Asteroid_id     object
H              float64
status           int64
family_1         int64
dv_fam_1       float64
near_1          object
family_2         int64
dv_fam_2       float64
near_2           int64
rescod          object
dtype: object

In [10]:
cols_rms = [
    "Asteroid_id",
    "rms_a",
    "rms_e",
    "rms_sin_i",
    "rms_n",
    "rms_g",
    "rms_s",
    "lam_fit_deg",
    "My"
]

In [11]:
RMS_mb_df = pd.read_csv("data/lvl0/RMS_main_belt.sig", delimiter='\s+', names=cols_rms, comment='%')

/tmp/ipykernel_13846/1244498015.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  RMS_mb_df = pd.read_csv("data/lvl0/RMS_main_belt.sig", delimiter='\s+', names=cols_rms, comment='%')

In [12]:
RMS_mb_df.head()

,Asteroid_id,rms_a,rms_e,rms_sin_i,rms_n,rms_g,rms_s,lam_fit_deg,My
0,1,4.710000e-06,0.001482,0.000029,0.000169,0.005767,0.055891,97.2642,-2
1,2,5.325000e-05,0.003741,0.000747,0.003584,0.017078,0.018003,3385.2442,10
2,3,4.010000e-06,0.000075,0.000030,0.000123,0.003290,0.005535,57.0721,-2
3,4,2.000000e-08,0.000121,0.000072,0.000001,0.003256,0.003553,1.9958,2
4,6,9.700000e-07,0.002005,0.000205,0.000043,0.010758,0.032849,28.8165,2

In [13]:
RMS_mb_df.dtypes

Asteroid_id     object
rms_a          float64
rms_e          float64
rms_sin_i      float64
rms_n          float64
rms_g          float64
rms_s          float64
lam_fit_deg    float64
My               int64
dtype: object

In [14]:
for df in [prop_df, family_df, RMS_mb_df]:
    df['Asteroid_id'] = df['Asteroid_id'].astype(str).str.strip()

In [15]:
# Normalizing the 'Asteroid_id' column across all dataframes.

print("Prop: ", prop_df['Asteroid_id'].dtype, "-----", len(prop_df))
print("Family: ", family_df['Asteroid_id'].dtype, "-----", len(family_df))
print("RMS: ", RMS_mb_df['Asteroid_id'].dtype, "-----", len(RMS_mb_df))

Prop:  object ----- 1152208
Family:  object ----- 1189931
RMS:  object ----- 1152208

In [16]:
pathlib.Path(os.path.join(core_path, "data/lvl1")).mkdir(parents=True, exist_ok=True)

prop_df.to_pickle(os.path.join(core_path, "data/lvl1", "prop_df.pkl"), protocol=4)
family_df.to_pickle(os.path.join(core_path, "data/lvl1", "family_df.pkl"), protocol=4)
RMS_mb_df.to_pickle(os.path.join(core_path, "data/lvl1", "RMS_mb_df.pkl"), protocol=4)